version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: laravel-backend
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: password
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
