version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: laravel-backend
    restart: always
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:zQAH+ivKNgPhT/NV3dzy+/TAV0nA0VffMeOzV6d3+2E=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=news_aggregator_db
      - DB_USERNAME=news_aggregator_user
      - DB_PASSWORD=123Aggregator987
    expose:
      - "9000" # Expose port for internal communication

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "9001:80"
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  # Database Service (MySQL or MariaDB)
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
